spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbms
    username: root
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
